### ISSUE TITLE
دانلود دروس به شکل تکی

### ISSUE THREAD

**Issue by aliafshany** [NabiKAZ/faradars-downloader#1]
سلام
عرض ادب خدمت شما
من بسیار ممنونم که همچین ربات جالبی رو اپن سورس گذاشتید.
میخواستم بدونم آیا ممکن هست که تغییرات لازم رو بهم یاد بدید تا صرفا یک کورس خریداری شده رو بشه دانلود کرد؟

**Comment by NabiKAZ** [comment]
سلام و ممنون که از این پروژه استفاده میکنید.

به طور کلی و از نظر فنی، باید کوکی هایی که برای لاگین به سایت استفاده میکنید رو در هدر درخواست تنظیم کنید. اونها رو از کنسول کروم و درخواست هایی که به سایت ارسال میشه میتونید بردارید و در کد هم در بخش curl به هدر اضافه کنید. بدین ترتیب کد شما به صفحات داخلی پنل کاربریتون دسترسی خواهد داشت.
در مرحله بعد باید صفحه محصول مورد نظر رو با الگویی که من در این پروژه نوشتم مقایسه کنید. شاید نیاز به آپدیت داشته باشد. یعنی الگویی که منجر به پیدا کردن آدرس ویدیوهای درون صفحه میشود را باید بررسی کنید که آیا همان برای صفحات محصولات خریداری شده کار میکند یا نیاز به تغییر دارد.

متاسفانه من سطح شما رو نمیدونم و حتی نمیدونم برنامه نویس هستید یا نه اما اگر که نیستید و تنها برای ساده شدن کارتون و یکبار میخوید دانلود کنید. یه راه ساده شاید این باشه که روی صفحه view source بزنید و اگر ویدیوها توی صفحه هستند از کل html صفحه کپی بگیرید و از گزینه add batch download from clipboard در IDM استفاده کنید تا تمام لینکها را شناسایی و یکجا دانلود کنید.

**Comment by aliafshany** [comment]
بسیار ممنون بابت جوابی که دادید
همین راهکار آخر خیلی ساده و کاربردی و خلاقانه  بود :)
🌺

**Comment by NabiKAZ** [comment]
خواهش میکنم.
برنامه هایی مثل webzip  هم میتونید امتحان کنید، کل یک سایت رو عیناً دانلود میکنند تا به شکل آفلاین بتونید در اون بچرخید.
