### ISSUE TITLE
آپدیت اسکریپت برای نسخه جدید سایت

### ISSUE THREAD

**Issue by NEOIR** [NabiKAZ/faradars-downloader#2]
با سلام
با توجه به تغییر نسخه جدید وبسایت فرادرس در صورت امکان اسکریپت رو به روزرسانی کنید، تشکر

**Comment by NabiKAZ** [comment]
این اسکریپت فقط برای طرح همون سال نوشته شده بود که چندین دوره رایگان شدند و دانلود تک تک اونها سخت بود.
اما برای دوره‌هایی که خریداری میشن فکر میکنم اونقدر زیاد نباشن که نیاز به اسکریپت خاصی باشه و خود سایت احتمالاً ابزار دانلود اونها رو فراهم کرده. اگرهم برای یک کورس، ویدیوهاش مجزا هستند و دانلود کل پک رو نمیده. شاید این راه حل بدرد شما هم بخوره چون اون دوستمون گفتند ازش جواب گرفتند:
https://github.com/NabiKAZ/faradars-downloader/issues/1#issuecomment-1079264608
